exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"
version: "2"
checks:
  method-complexity:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 300
  identical-code:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 35
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 50
  string-concatenation:
    config:
    threshold: 3
  switch-statements:
    config:
    threshold: 3
  file-complexity:
    config:
    threshold: 10
  method-arguments:
    config:
    threshold: 4
  method-cognitive-complexity:
    config:
    threshold: 5
  method-definitions:
    config:
    threshold: 10
  method-locations:
    config:
    threshold: 10
  method-parameters:
    config:
    threshold: 5
  method-size:
    config:
    threshold: 25
  method-variables:
    config:
    threshold: 5
  new-lines:
    config:
    threshold: 3
  number-of-lines:
    config:
    threshold: 500
  number-of-methods:
    config:
    threshold: 50
  number-of-parameters:
    config:
    threshold: 10
  number-of-variables:
    config:
    threshold: 10
  number-of-children:
    config:
    threshold: 10
  number-of-classes:
    config:
    threshold: 10
  number-of-files:
    config:
    threshold: 10
  number-of-functions:
    config:
    threshold: 10
  number-of-lines-of-code:
    config:
    threshold: 1000
  number-of-statements:
    config:
    threshold: 100
  number-of-try-catch:
    config:
    threshold: 3
  number-of-try-catch-finally:
    config:
    threshold: 3
  number-of-try-finally:
    config:
    threshold: 3
  number-of-try-resources:
    config:
    threshold: 3
  number-of-try-with-resources:
    config:
    threshold: 3